### ISSUE TITLE
当有数字为名字的时候，比如：3 ，会出现分组错乱

### ISSUE THREAD

**Issue by mydy1987** [icoder20150719/ICPingyinConvert#1]
这是我在Github上找到的最好的通讯录分组库，
谢谢，可以少掉好多工作量，能站在巨人肩上。
请看下标题上的bug,能处理一下，就完美了。

**Comment by icoder20150719** [comment]
很抱歉最近没有关注这个邮箱，你提的问题很好，我已经提交了代码，不知能否解决你的问题？有什么问题请随时issues我

发自 网易邮箱大师
在2015年12月11日 11:24，mydy1987 写道:

这是我在Github上找到的最好的通讯录分组库，
